### ISSUE TITLE
Board test function not working

### ISSUE THREAD

**Issue by Simulators** [robdobsn/PiBusRaider#3]
Firmware 2.2.051 (Pi & ESP), BusRaider board revision 2.01.

- BusRaider is the only board on the RC2014 Pro backplane.
- NMI/Page/Clk jumpers all installed. 
- Pi-ESP1 and Z80-ESP2 jumpers installed. 
- Z80-Serial1 jumpers installed.

Board boots OK, Wifi connects, HDMI and keyboard OK. Web UI works. F2 brings up Immediate Mode. Memory test (m) works (and - correctly - fails as no memory board is installed). Bit test (b) appears to work, pressing space cycles through the tests and eventually returns to Normal mode.

**Board test (t) does not work.** Entering "t" displays "t" in the right-hand status area, pressing return then does nothing, no further output at all. Board appears to be hung, refresh rate spinner stops. Web server still serves the config page, but no web UI functions work. Power cycle or Pi reset button is required to regain control. After entering "t"/return, while board is apparently in hung state, Pi green LED is flashing rapidly at about 5Hz. This stops when the Pi is reset.

Board test worked with the same hardware and f/w 2.0.39. Not got time to revert and retest right now.

In all other respects the board appears to be working fine. Adding Z80 CPU and Spencer's 64K RAM board I can load Spectrum and TRS80 ROM images OK. Switching to Rob's 1MB RAM card (in RAM+RAM configuration) I can load RomWBW OK.

**Comment by robdobsn** [comment]
Hi

Apologies for the delay in responding. Did you make progress with this?

The rapid flashing of the Pi LED means the Pi has crashed unfortunately. So that’s a definite bug.

I’m going to take a look at this now.

Regards

Rob

Rob Dobson FIET
rob@dobson.com
+44 7770 866452
http://LinkedIn.com/in/robdobsn
@robdobsn www.robdobson.com

**Comment by Simulators** [comment]
Hi Rob,

No, not had time to do anything much else with it at the moment. Is there
any additional debugging I can collect for you on this?

Regards
Andrew

**Comment by robdobsn** [comment]
Finally found a solution which seems to be toolchain related. The code for board test works when compiled with an earlier ARM cross compiler (2019 linux I think) but fails on 2020 compiler. Commenting out code from the test function gets it working again and the solution I've implemented is simply to shorten the test function by moving code to a sub-function and calling that instead of inline.
